In [9]:
import numpy as np

In [37]:
#ЗАВДАННЯ 1

#Створіть одновимірний масив (вектор) з простими числами, не перевищуючи 70, та виведіть його значення.

# Створюємо одновимірний масив простих чисел до 70
vector = np.array([num for num in range(2, 71) if all(num % i != 0 for i in range(2, int(np.sqrt(num)) + 1))])

# Виводимо масив простих чисел
print("Масив простих чисел до 70:")
print(vector)



Масив простих чисел до 70:
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67]


In [38]:
#ЗАВДАННЯ 2

# Створюємо одновимірний масив квадратів перших 9 натуральних чисел
squares = np.array([n**2 for n in range(1, 10)])

# Перетворюємо одновимірний масив у двовимірний масив розміром 3x3
matrix = squares.reshape(3, 3)

# Виводимо матрицю
print("Матриця 3x3, заповнена квадратами перших натуральних чисел:")
print(matrix)

Матриця 3x3, заповнена квадратами перших натуральних чисел:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [39]:
#ЗАВДАННЯ 3

#Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до 10 та знайдіть максимальний елемент

# Створюємо масив розміром 5x5 з випадковими цілими числами від -10 до 10
matrix = np.random.randint(-10, 11, size=(5, 5))

# Знаходимо максимальний елемент масиву
max_element = np.max(matrix)

# Виводимо масив та максимальний елемент
print("Масив 5x5, заповнений випадковими числами від -10 до 10:")
print(matrix)
print("\nМаксимальний елемент масиву:", max_element)

Масив 5x5, заповнений випадковими числами від -10 до 10:
[[ -4   0  -6 -10  -9]
 [ 10   5   3   5   0]
 [ -2 -10   1  -1  -5]
 [  4  -6   9   0  -5]
 [  0   0  -9  -8   6]]

Максимальний елемент масиву: 10


In [40]:
#ЗАВДАННЯ 4

# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить максимальні елементи в кожному стовпці.

matrix = np.random.rand(4, 4)

# Знаходимо максимальні елементи в кожному стовпці
max_elements = np.max(matrix, axis=0)

# Виводимо масив та вектор-рядок з максимальними елементами в кожному стовпці
print("Масив 4x4, заповнений випадковими дійсними числами від 0 до 1:")
print(matrix)
print("\nВектор-рядок з максимальними елементами в кожному стовпці:")
print(max_elements)

Масив 4x4, заповнений випадковими дійсними числами від 0 до 1:
[[0.01060694 0.5312235  0.36895155 0.95752141]
 [0.06947619 0.75892061 0.17254131 0.74241463]
 [0.3537759  0.54279717 0.61443588 0.72673283]
 [0.07362316 0.97302699 0.21752635 0.04502841]]

Вектор-рядок з максимальними елементами в кожному стовпці:
[0.3537759  0.97302699 0.61443588 0.95752141]


In [41]:
#ЗАВДАННЯ 5

#Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

array1 = np.random.randint(-10, 11, size=7)
array2 = np.random.randint(-10, 11, size=7)

# Поелементні операції додавання, віднімання та множення
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виводимо результати
print("Перший масив:")
print(array1)
print("\nДругий масив:")
print(array2)

print("\nРезультат додавання:")
print(addition)
print("\nРезультат віднімання:")
print(subtraction)
print("\nРезультат множення:")
print(multiplication)

Перший масив:
[ 4 -1  6  2  5 -3  8]

Другий масив:
[-1 10 -5  3 -5 -9  1]

Результат додавання:
[  3   9   1   5   0 -12   9]

Результат віднімання:
[  5 -11  11  -1  10   6   7]

Результат множення:
[ -4 -10 -30   6 -25  27   8]


In [42]:
#ЗАВДАННЯ 6

#Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -10 до 10 та знайдіть їх добуток.

matrix1 = np.random.randint(-10, 11, size=(4, 4))
matrix2 = np.random.randint(-10, 11, size=(4, 4))

# Знаходимо добуток двох матриць
product_matrix = np.dot(matrix1, matrix2)

# Виводимо матриці та їхній добуток
print("Перша матриця 4x4:")
print(matrix1)
print("\nДруга матриця 4x4:")
print(matrix2)
print("\nДобуток двох матриць:")
print(product_matrix)

Перша матриця 4x4:
[[ -8  10   9   5]
 [ -7   4  -9   1]
 [  7  -8  -8   7]
 [ -9   0 -10  -2]]

Друга матриця 4x4:
[[10 -5  8  4]
 [-4  5  0 -7]
 [ 9  6 -5  0]
 [ 3  5  6  0]]

Добуток двох матриць:
[[ -24  169  -79 -102]
 [-164    6   -5  -56]
 [  51  -88  138   84]
 [-186  -25  -34  -36]]


In [69]:
#ЗАВДАННЯ 7

# Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та перемножте їх між собою

matrix1 = np.random.randint(1, 4, size=(4, 2))
matrix2 = np.random.randint(1, 4, size=(2, 2))
product_matrix = np.dot(matrix1, matrix2)

print("Перша матриця 4x2:")
print(matrix1)
print("\nДруга матриця 2x2:")
print(matrix2)
print("\nДобуток матриць:")
print(product_matrix)

Перша матриця 4x2:
[[2 2]
 [2 2]
 [2 1]
 [1 3]]

Друга матриця 2x2:
[[1 2]
 [2 3]]

Добуток матриць:
[[ 6 10]
 [ 6 10]
 [ 4  7]
 [ 7 11]]


In [68]:
#ЗАВДАННЯ 8

#Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

matrix = np.random.randint(1, 8, size=(2, 2))

det = np.linalg.det(matrix)
if det == 0:
    print("Матриця не є оберненою, оскільки детермінант дорівнює нулю.")
else:
    inverse_matrix = np.linalg.inv(matrix)

    print("Оригінальна матриця 2x2:")
    print(matrix)
    print("\nОбернена матриця 2x2:")
    print(inverse_matrix)

Оригінальна матриця 2x2:
[[1 2]
 [7 2]]

Обернена матриця 2x2:
[[-0.16666667  0.16666667]
 [ 0.58333333 -0.08333333]]


In [67]:
#ЗАВДАННЯ 9

##9 Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

matrix = np.random.randint(0, 2, size=(3, 5))
transposed_matrix = np.transpose(matrix)

print("Оригінальна матриця 3x5:")
print(matrix)
print("\nТранспонована матриця 5x3:")
print(transposed_matrix)

Оригінальна матриця 3x5:
[[0 0 0 1 1]
 [0 1 0 1 1]
 [1 1 0 1 1]]

Транспонована матриця 5x3:
[[0 0 1]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


In [66]:
#ЗАВДАННЯ 10

#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор

matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=(4, 1))
product = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)
print("\nДобуток матриці на вектор:")
print(product)

Матриця 3x4:
[[0.06278305 0.34223129 0.22440873 0.51752155]
 [0.20195083 0.23288516 0.4659016  0.80255168]
 [0.45270131 0.440873   0.24642613 0.24116038]]

Вектор 4x1:
[[4]
 [3]
 [9]
 [8]]

Добуток матриці на вектор:
[[ 7.4376771 ]
 [12.11998659]
 [ 7.28054243]]


In [65]:
#ЗАВДАННЯ 11

#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які менше за відповідний елемент вектору.

matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)

comparison_matrix = matrix < vector.T
sum_elements = np.sum(matrix[comparison_matrix])

print("Матриця 2x3:")
print(matrix)
print("\nВектор 3x1:")
print(vector)
print("\nСума елементів матриці, які менші за відповідний елемент вектору:")
print(sum_elements)

Матриця 2x3:
[[0.49192323 0.23099929 0.25285356]
 [0.04861962 0.61043924 0.79226177]]

Вектор 3x1:
[[0.9283147 ]
 [0.79732036]
 [0.86506341]]

Сума елементів матриці, які менші за відповідний елемент вектору:
2.4270967148402303


In [64]:
#ЗАВДАННЯ 12

#Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму

matrix1 = np.random.randint(1, 11, size=(8, 8))

matrix2 = np.random.randint(1, 11, size=(8, 8))

sum_matrix = matrix1 + matrix2

print("Перша матриця 8x8:")
print(matrix1)
print("\nДруга матриця 8x8:")
print(matrix2)
print("\nСума матриць:")
print(sum_matrix)

Перша матриця 8x8:
[[ 5  8  2  5  3  8  7  9]
 [10  3  5  2  6  7  3  1]
 [ 7  1  4  3  6  9  1  1]
 [ 5  5  1  8  2  6  8  6]
 [10  4  1  4  8  5  8  4]
 [10  7  2 10  5  3  4  8]
 [ 1  1  7  1 10  9  1  3]
 [ 2  9  8  3  8  3  2  2]]

Друга матриця 8x8:
[[10  6  2  9  3  3  5  4]
 [ 9  3  6  1  7 10  4  5]
 [ 8  2  6  8  2  4  4 10]
 [ 6  8  1  1  4  3  5  6]
 [ 5  3  8  8  6  1  1  9]
 [ 3  9 10  2  9  2  6  3]
 [ 1  7  8  2  1  4  1  3]
 [ 2  8  1 10  1  6  3  2]]

Сума матриць:
[[15 14  4 14  6 11 12 13]
 [19  6 11  3 13 17  7  6]
 [15  3 10 11  8 13  5 11]
 [11 13  2  9  6  9 13 12]
 [15  7  9 12 14  6  9 13]
 [13 16 12 12 14  5 10 11]
 [ 2  8 15  3 11 13  2  6]
 [ 4 17  9 13  9  9  5  4]]


In [63]:
#ЗАВДАННЯ 13

#Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть добуток їх елементів.

matrix1 = np.random.uniform(-1, 1, size=(3, 3))
matrix2 = np.random.uniform(-1, 1, size=(3, 3))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

matrix = matrix1 * matrix2

print("Матриця, отримана в результаті добутку елементів:\n", matrix)

Перша матриця:
 [[ 0.85227554 -0.41149326 -0.81860142]
 [-0.38065232 -0.28506781  0.31848221]
 [ 0.81354652 -0.69421255 -0.99130479]]
Друга матриця:
 [[ 0.67359676  0.58302607  0.12695159]
 [ 0.11371476  0.56332709 -0.01875597]
 [ 0.97317342 -0.99973016  0.44744325]]
Матриця, отримана в результаті добутку елементів:
 [[ 0.57409005 -0.2399113  -0.10392275]
 [-0.04328579 -0.16058642 -0.00597344]
 [ 0.79172184  0.69402523 -0.44355263]]


In [62]:
#ЗАВДАННЯ 14

#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть добуток елементів матриці, які більше за їх середнє арифметичне значення

matrix = np.random.uniform(-5, 5, size=(3, 3))
print("Матриця:\n", matrix)

mean_value = np.mean(matrix)
print("Середнє арифметичне:", mean_value)

elements = matrix[matrix > mean_value]
product = np.prod(elements) if elements.size > 0 else 0
print("Добуток елементів більших за середнє:", product)

Матриця:
 [[ 3.58587735 -2.32199098  4.8610787 ]
 [ 4.83514725 -0.73698636 -1.03642765]
 [ 4.20048969 -0.13299636  0.786257  ]]
Середнє арифметичне: 1.5600498498633928
Добуток елементів більших за середнє: 354.02808124016497


In [60]:
# Створення матриці 3x3 з випадковими числами
matrix = np.random.uniform(-0.5, 0.5, size=(3, 3))
print("Матриця:\n", matrix)


def find_max_int(row):
    rounded_row = np.round(row)
    max_index = np.argmax(np.abs(rounded_row))
    return rounded_row[max_index]

result_vector = np.apply_along_axis(find_max_int, 1, matrix).reshape(-1, 1)

print("Вектор-стовпчик з найбільшими за модулем цілими значеннями:\n", result_vector)

Матриця:
 [[-0.41664608  0.4400107  -0.02736484]
 [-0.24043793  0.0360715   0.31523415]
 [-0.15221091 -0.10870202  0.31760667]]
Вектор-стовпчик з найбільшими за модулем цілими значеннями:
 [[-0.]
 [-0.]
 [-0.]]
